export * as db from "./db/client.js"
export * as migrate from "./db/migrate.js"
export { getMigrationStatus, runMigrations } from "./db/migrate.js"
export * as schema from "./db/schema.js"
export * from "./errors.js"
export * from "./features/auto-tags/index.js"
export * from "./features/extract/service.js"
export * from "./features/items/service.js"
export * from "./features/status/service.js"
export * from "./features/tags/service.js"
export * from "./features/tts/doctor.js"
export * from "./features/tts/jobs.js"
export * from "./features/tts/service.js"
export * as paths from "./lib/paths.js"
export { DEFAULT_AUDIO_DIR, DEFAULT_DB_PATH, resolveAudioDir, resolveDbPath } from "./lib/paths.js"
export * from "./services/index.js"
export * from "./types.js"
